//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tvosem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс билета.
    /// </summary>
    // *** Start programmer edit section *** (КлассБилета CustomAttributes)

    // *** End programmer edit section *** (КлассБилета CustomAttributes)
    public enum КлассБилета
    {
        
        // *** Start programmer edit section *** (КлассБилета.Эконом CustomAttributes)

        // *** End programmer edit section *** (КлассБилета.Эконом CustomAttributes)
        [Caption("Эконом")]
        Эконом,
        
        // *** Start programmer edit section *** (КлассБилета.Бизнес CustomAttributes)

        // *** End programmer edit section *** (КлассБилета.Бизнес CustomAttributes)
        [Caption("Бизнес")]
        Бизнес,
        
        // *** Start programmer edit section *** (КлассБилета.Первый CustomAttributes)

        // *** End programmer edit section *** (КлассБилета.Первый CustomAttributes)
        [Caption("Первый")]
        Первый,
    }
}
