//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tvosem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Код брони.
    /// </summary>
    // *** Start programmer edit section *** (КодБрони CustomAttributes)

    // *** End programmer edit section *** (КодБрони CustomAttributes)
    [AutoAltered()]
    [Caption("Код бронирования")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КодБрониE", new string[] {
            "Код as \'Код\'"})]
    [View("КодБрониL", new string[] {
            "Код as \'Код\'"})]
    public class КодБрони : ICSSoft.STORMNET.DataObject
    {
        
        private string fКод;
        
        // *** Start programmer edit section *** (КодБрони CustomMembers)

        // *** End programmer edit section *** (КодБрони CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (КодБрони.Код CustomAttributes)

        // *** End programmer edit section *** (КодБрони.Код CustomAttributes)
        [StrLen(255)]
        public virtual string Код
        {
            get
            {
                // *** Start programmer edit section *** (КодБрони.Код Get start)

                // *** End programmer edit section *** (КодБрони.Код Get start)
                string result = this.fКод;
                // *** Start programmer edit section *** (КодБрони.Код Get end)

                // *** End programmer edit section *** (КодБрони.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КодБрони.Код Set start)

                // *** End programmer edit section *** (КодБрони.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (КодБрони.Код Set end)

                // *** End programmer edit section *** (КодБрони.Код Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КодБрониE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КодБрониE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КодБрониE", typeof(IIS.Tvosem.КодБрони));
                }
            }
            
            /// <summary>
            /// "КодБрониL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КодБрониL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КодБрониL", typeof(IIS.Tvosem.КодБрони));
                }
            }
        }
    }
}
